from __future__ import annotations

EXCLUDE_DIRS = {
    ".git",
    "node_modules",
    "vendor",
    ".next",
    "dist",
    "build",
    "coverage",
    "logs",
    ".turbo",
    ".vercel",
    "out",
    "target",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "venv",
    ".venv",
    ".tox",
    ".gradle",
    ".idea",
    ".vscode",
}

SOURCE_EXTS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".mjs",
    ".cjs",
    ".go",
    ".rs",
    ".rb",
    ".java",
    ".kt",
    ".kts",
    ".swift",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".hpp",
    ".cs",
    ".php",
    ".vue",
    ".svelte",
    ".sh",
    ".bash",
    ".zsh",
    ".sql",
}

MANIFEST_NAMES = {
    "package.json",
    "tsconfig.json",
    "next.config.js",
    "next.config.mjs",
    "next.config.ts",
    "nuxt.config.js",
    "nuxt.config.ts",
    "vite.config.js",
    "vite.config.ts",
    "angular.json",
    "svelte.config.js",
    "svelte.config.ts",
    "nest-cli.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "package-lock.json",
    "yarn.lock",
    "requirements.txt",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "Pipfile",
    "poetry.lock",
    "pytest.ini",
    "tox.ini",
    "conftest.py",
    "composer.json",
    "go.mod",
    "go.work",
    "Cargo.toml",
    "pom.xml",
    "settings.gradle",
    "settings.gradle.kts",
    "build.gradle",
    "build.gradle.kts",
    "Gemfile",
    "Makefile",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "turbo.json",
    "nx.json",
    "lerna.json",
}

CI_NAMES = {
    ".github/workflows",
    ".gitlab-ci.yml",
    "Jenkinsfile",
    ".circleci",
    ".travis.yml",
    "azure-pipelines.yml",
    "bitbucket-pipelines.yml",
}

CONVENTION_FILES = ["CLAUDE.md", "AGENTS.md", ".cursorrules", "CONTRIBUTING.md"]

LARGE_FILE_THRESHOLD = 300
HIGH_FILE_THRESHOLD = 1500
MEDIUM_FILE_THRESHOLD = 500

SEVERITY_ORDER = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
SEVERITY_WEIGHTS = {"critical": 20, "high": 10, "medium": 5, "low": 1, "info": 0}

EXTENSION_LANGUAGE = {
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".py": "Python",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".fs": "F#",
    ".swift": "Swift",
    ".c": "C/C++",
    ".cc": "C/C++",
    ".cpp": "C/C++",
    ".h": "C/C++",
    ".hpp": "C/C++",
    ".vue": "Vue",
    ".svelte": "Svelte",
}
